/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./public/**/*.html"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#12131a",
        "on-surface": "#e1e2ec",
        "on-surface-variant": "#c3c6d6",
        "surface-container-low": "#1c1e26",
        "primary": "#0052cc",
        "on-secondary-fixed": "#021945",
        "secondary-container": "#344573",
        "surface-variant": "#434654",
        "tertiary-fixed-dim": "#00daf3",
        "on-secondary-fixed-variant": "#b6c8fe",
        "tertiary-container": "#004a54",
        "surface-tint": "#b2c5ff",
        "surface-bright": "#2e3038",
        "error": "#ffb4ab",
        "surface-container-high": "#282a34",
        "surface": "#191b23",
        "primary-fixed": "#dae2ff",
        "tertiary": "#00daf3",
        "on-tertiary-fixed-variant": "#004f58",
        "surface-container": "#23252e",
        "tertiary-fixed": "#9cf0ff",
        "inverse-on-surface": "#191b23",
        "secondary-fixed": "#dae2ff",
        "on-tertiary-fixed": "#001f24",
        "primary-fixed-dim": "#b2c5ff",
        "primary-container": "#003d9b",
        "error-container": "#93000a",
        "on-primary-container": "#dae2ff",
        "surface-container-highest": "#33353f",
        "surface-container-lowest": "#0d0e14",
        "outline": "#8d919f",
        "on-error-container": "#ffdad6",
        "on-background": "#e1e2ec",
        "inverse-primary": "#0052cc",
        "inverse-surface": "#e1e2ec",
        "on-error": "#690005",
        "background": "#0d0e14",
        "on-tertiary-container": "#33e6ff",
        "secondary-fixed-dim": "#b4c5fb",
        "secondary": "#b4c5fb",
        "on-primary": "#ffffff",
        "outline-variant": "#434654",
        "on-secondary": "#1b2d5b",
        "on-tertiary": "#00363d",
        "on-secondary-container": "#dbe1ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
